inherit_from: .rubocop_todo.yml

# This is the configuration used to check the rubocop source code.

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - "db/schema.rb"
    - "lib/tasks/*.rake"
    - "bin/*"
    - "config/puma.rb"
    - "config/spring.rb"
    - "config/initializers/*"
    - "config/environments/development.rb"
    - "config/environments/test.rb"
    - "config/environments/production.rb"
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - "spec/spec_helper.rb"
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Exclude:
    - 'app/serializers/panko_serializers/*'

