inherit_from: .rubocop_todo.yml

# This is the configuration used to check the rubocop source code.

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/**/*'
    - 'config/application.rb'
    - 'spec/spec_helper.rb'
    - 'Rakefile'
    - 'vendor/bundle/**/*'
    - Capfile

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Naming/MethodName:
  Exclude:
    - 'app/serializers/panko_serializers/*'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/performance/searching/*'
    - 'spec/performance/serializing/*'

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 15

RSpec/MessageChain:
  Enabled: false
